config/routes.rb
Rails.application.routes.draw do
  root 'groups#index'

  devise_for :users

  resources :groups, only: [:index, :new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  end

  resources :users, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :messages
  has_many :users, through: :groups_users
  has_many :groups_users
  accepts_nested_attributes_for :groups_users
  validates :name, presence: true

    def show_message
      if last_message = messages.last
         last_message.body
      else
         "まだメッセージはありません"
      end
    end
end

app/models/groups_user.rb
class GroupsUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
  validates :body, presence: true, if: ->{image.blank?}

   mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :messages
  has_many :groups, through: :groups_users
  has_many :groups_users
  accepts_nested_attributes_for :groups_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?



  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: [:edit, :update]

  def new
    @group = Group.new
  end

  def create
    @group = Group.create(group_params)
    if @group.save
      redirect_to group_messages_path(@group) , notice: "チャットグループが作成されました"
    else
      flash.now[:alert] = "チャットグループは作成されていません"
      render action: :new
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group) , notice: "チャットグループが更新されました"
    else
      flash.now[:alert] = "チャットグループが更新されませんでした"
      render action: :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group

  def index
    @message = Message.new
    @groups = current_user.groups
    @messages = Message.includes(:user)
  end

  def create
    @message = @group.messages.build(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path}
        format.json
      end
    else
      redirect_to group_messages_path, alert: "メッセージを入力してください"
    end
  end

  private
  def message_params
    params.require(:message).permit(:body, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

  # test
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.where('name LIKE ?', "%#{params[:name]}%")
    render json: @users
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/common/_error.html.haml
-if error.any?
  .chat-group-form__errors
    %h2= "#{error.count} error prohibited this chat_group from being saved:"
    %ul
      -error.full_messages.each do |msg|
        %li= msg

app/views/groups/_form.html.haml
= form_for @group, html: { class: "edit_chat_group", id: "edit_chat_group" } do |f|
  = render partial: "common/error", locals: { error: @group.errors }
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :name, :グループ名, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, placeholder: "グループ名を入力してください", id: 'chat-group_name', class: 'chat-group-form__input'
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :チャットメンバーを追加, class: 'chat-group-form__label'
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input#chat-group_user.chat-group-form__input{ type: "text", placeholder: '追加したいユーザー名を入力してください' }
      #user-search-result
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :チャットメンバー, class: 'chat-group-form__label'
    .chat-group-form__field--right
      #chat-group-users
        #chat-group-user.chat-group-user.clearfix
          = f.hidden_field :user_ids, class: 'chat-group-form_hidden'
          %p.chat-group-add-user__name{id: current_user.id}
            =current_user.name
  .chat-group-form__field.clearfix
    .chat-group-form__field--right
      = f.submit :Save, name:'commit', value: 'Save', class: 'chat-group-form__action-btn', disable_with: 'Save'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render 'form'

app/views/groups/index.html.haml
.chat
  .chat-side
    .chat__user
      %p= current_user.name
      = link_to edit_user_registration_path do
        %i.fa.fa-cog.icon-cog
      = link_to new_group_path do
        %i.fa.fa-edit.icon-edit
    .chat__groups
      -  current_user.groups.each do |group|
        = link_to group_messages_path(group) do
          .group-link
            .group-name= group.name
            .group-text= group.show_message

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render 'form'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    -flash.each do |key, value|
      =content_tag :div, value, class: "flash-#{key}"
    = yield

app/views/messages/_chat-main.haml
.chat-main
  .chat-header
    = render partial: 'group', collrction: @groups
    .chat-header--right
      =link_to edit_group_path(@group) do
        .button Edit
  .chat__message--display
    = render partial: 'message', collrction: @messages
  .chat__message--input
    = form_for [@group, @message] do |f|
      .message-body
        = f.text_field :body, placeholder: "メッセージを入力してください", class: "message-type" 
        %label.chat-footer__

app/views/messages/_chat-side.haml
.chat-side
  .chat__user
    %p= current_user.name
    = link_to edit_user_registration_path do
      %i.fa.fa-cog.icon-cog
    = link_to new_group_path do
      %i.fa.fa-edit.icon-edit
  .chat__groups
    -  current_user.groups.each do |group|
      = link_to group_messages_path(group) do
        .group-link
          .group-name= group.name
          .group-text= group.show_message

app/views/messages/_group.html.haml
.chat-header--left
  %p= @group.name
  .group-members 
  Members:
  - @group.users.each do |user|
    = user.name

app/views/messages/_message.html.haml
.messages
- @group.messages.each do |message|
  .message-user 
    = message.user.name
  .message-time 
    = message.created_at
  .message-text
    = message.body
    %br
    = image_tag message.image if message.image?

app/views/messages/index.html.haml
.chat
  = render 'chat-side'
  .chat-main
    .chat-header
      = render partial: 'group', collrction: @groups
      .chat-header--right
        =link_to edit_group_path(@group) do
          .button Edit
    .chat__message--display
      = render partial: 'message', collrction: @messages
    .chat__message--input
      = form_for [@group, @message] do |f|
        .message-body
          = f.text_field :body, placeholder: "メッセージを入力してください", class: "message-type" 
          %label.chat-footer__file
            = f.file_field :image
            %i.fa.fa-image
        = f.submit "Send", class: "send-button" 